# SPDX-FileCopyrightText: Copyright 2026, Slinky Software
# SPDX-License-Identifier: GPL-3.0-only

# Generated by Django 6.0.6 on 2026-08-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_source',
            field=models.CharField(choices=[('entra', 'Entra'), ('ldap', 'LDAP'), ('oidc', 'OIDC/OAuth'), ('local', 'Local')], default='local', max_length=16),
        ),
    ]
