# Generated by Django 5.2.15 on 2026-06-15 05:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_number', models.CharField(max_length=64, unique=True)),
                ('source_partition', models.CharField(default='INTERNAL', max_length=255)),
                ('cached_current_destination', models.CharField(blank=True, default='', max_length=255)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_by_text', models.CharField(blank=True, default='', max_length=255)),
                ('created_by_text', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diversions', to='access_groups.accessgroup')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
