# SPDX-FileCopyrightText: Copyright 2026, Slinky Software
# SPDX-License-Identifier: GPL-3.0-only

# Generated by Django 6.0.6 on 2026-10-06 10:46

import audiocodes_cdr.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdr',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cdrtype', models.CharField(max_length=255, null=True)),
                ('reporttype', models.CharField(max_length=255, null=True)),
                ('callid', models.CharField(max_length=255, null=True)),
                ('globalsessionid', models.CharField(max_length=255, null=True)),
                ('sessionid', models.CharField(max_length=255, null=True)),
                ('legid', models.BigIntegerField(null=True)),
                ('callerdisplayid', models.CharField(max_length=255, null=True)),
                ('sourceusernamebeforemanip', models.CharField(max_length=255, null=True)),
                ('sourceusername', models.CharField(max_length=255, null=True)),
                ('sourcetags', models.CharField(max_length=255, null=True)),
                ('calleedisplayid', models.CharField(max_length=255, null=True)),
                ('destinationusernamebeforemanip', models.CharField(max_length=255, null=True)),
                ('destinationusername', models.CharField(max_length=255, null=True)),
                ('destinationtags', models.CharField(max_length=255, null=True)),
                ('sipinterfacename', models.CharField(max_length=255, null=True)),
                ('ipgroupname', models.CharField(max_length=255, null=True)),
                ('proxysetname', models.CharField(max_length=255, null=True)),
                ('remoteip', models.CharField(max_length=255, null=True)),
                ('remoteport', models.BigIntegerField(null=True)),
                ('remotertpip', models.CharField(max_length=255, null=True)),
                ('remotertpport', models.BigIntegerField(null=True)),
                ('codertype', models.CharField(max_length=255, null=True)),
                ('callorig', models.CharField(max_length=255, null=True)),
                ('terminationside', models.CharField(max_length=255, null=True)),
                ('cdrtrigger', models.CharField(max_length=255, null=True)),
                ('alertingtime', models.BigIntegerField(null=True)),
                ('callduration', models.BigIntegerField(null=True)),
                ('wascallstarted', models.BooleanField(null=True)),
                ('callsuccess', models.BooleanField(null=True)),
                ('setuptime', models.DateTimeField(null=True)),
                ('connecttime', models.DateTimeField(null=True)),
                ('releasetime', models.DateTimeField(null=True)),
                ('terminationreason', models.CharField(max_length=255, null=True)),
                ('terminationreasoncategory', models.CharField(max_length=255, null=True)),
                ('sipterminationreason', models.CharField(max_length=255, null=True)),
                ('sipterminationdescription', models.CharField(max_length=255, null=True)),
                ('terminationsideradius', models.CharField(max_length=255, null=True)),
                ('terminationsideyesno', models.BooleanField(null=True)),
                ('terminationreasonvalue', models.BigIntegerField(null=True)),
                ('localjitter', models.BigIntegerField(null=True)),
                ('localpacketloss', models.BigIntegerField(null=True)),
                ('localroundtripdelay', models.BigIntegerField(null=True)),
                ('remotejitter', models.BigIntegerField(null=True)),
                ('remotepacketloss', models.BigIntegerField(null=True)),
                ('remoteroundtripdelay', models.BigIntegerField(null=True)),
                ('varcalluserdefined1', models.CharField(max_length=255, null=True)),
                ('varcalluserdefined2', models.CharField(max_length=255, null=True)),
                ('varcalluserdefined3', models.CharField(max_length=255, null=True)),
                ('varcalluserdefined4', models.CharField(max_length=255, null=True)),
                ('varcalluserdefined5', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'cdr',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Sdr',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('recordtype', models.CharField(max_length=255, null=True)),
                ('sessionid', models.CharField(max_length=255, null=True)),
                ('setuptime', models.DateTimeField(null=True)),
                ('connecttime', models.DateTimeField(null=True)),
                ('releasetime', models.DateTimeField(null=True)),
                ('timetoconnect', models.BigIntegerField(null=True)),
                ('callduration', models.CharField(max_length=255, null=True)),
                ('sourceip', models.CharField(max_length=255, null=True)),
                ('destinationip', models.CharField(max_length=255, null=True)),
                ('ingressipgroup', models.CharField(max_length=255, null=True)),
                ('egressipgroup', models.CharField(max_length=255, null=True)),
                ('ingressani', models.CharField(max_length=255, null=True)),
                ('ingressdnis', models.CharField(max_length=255, null=True)),
                ('egressani', models.CharField(max_length=255, null=True)),
                ('egressdnis', models.CharField(max_length=255, null=True)),
                ('ingresscallid', models.CharField(max_length=255, null=True)),
                ('egresscallid', models.CharField(max_length=255, null=True)),
                ('ingressremotertpip', models.CharField(max_length=255, null=True)),
                ('ingressremotertpport', models.BigIntegerField(null=True)),
                ('egressremotertpip', models.CharField(max_length=255, null=True)),
                ('egressremotertpport', models.BigIntegerField(null=True)),
                ('globalsessionid', models.CharField(max_length=255, null=True)),
                ('ingressterminationreason', models.CharField(max_length=255, null=True)),
                ('egressterminationreason', models.CharField(max_length=255, null=True)),
                ('ingresssipterminationreason', models.CharField(max_length=255, null=True)),
                ('egresssipterminationreason', models.CharField(max_length=255, null=True)),
                ('issuccess', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'sdr',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CdrModuleSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('active_source', models.CharField(choices=[('replica', 'Read replica'), ('primary', 'Primary')], default='replica', max_length=16)),
                ('max_page_size', models.PositiveIntegerField(default=500)),
                ('max_multiselect_values', models.PositiveIntegerField(default=50)),
                ('lookup_cache_seconds', models.PositiveIntegerField(default=900)),
                ('statistics_cache_seconds', models.PositiveIntegerField(default=300)),
                ('termination_lookup_days', models.PositiveIntegerField(default=30)),
                ('hourly_bucket_max_hours', models.PositiveIntegerField(default=168)),
                ('user_defined_fields', models.JSONField(blank=True, default=audiocodes_cdr.models.default_user_defined_fields)),
                ('media_quality', models.JSONField(blank=True, default=audiocodes_cdr.models.default_media_quality)),
                ('field_help_overrides', models.JSONField(blank=True, default=dict)),
                ('config_version', models.PositiveIntegerField(default=1)),
                ('updated_by_text', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'AudioCodes CDR module settings',
            },
        ),
        migrations.CreateModel(
            name='CdrSourceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('replica', 'Read replica'), ('primary', 'Primary')], max_length=16, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=5432)),
                ('database_name', models.CharField(max_length=63)),
                ('username', models.CharField(max_length=63)),
                ('password_encrypted', models.TextField(blank=True, default='')),
                ('sslmode', models.CharField(choices=[('disable', 'disable'), ('prefer', 'prefer'), ('require', 'require'), ('verify-ca', 'verify-ca'), ('verify-full', 'verify-full')], default='prefer', max_length=16)),
                ('sslrootcert', models.CharField(blank=True, default='', max_length=1024)),
                ('connect_timeout', models.PositiveSmallIntegerField(default=10)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('role',),
            },
        ),
        migrations.CreateModel(
            name='CdrUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_format', models.CharField(choices=[('seconds', 'Decimal seconds'), ('hms', 'HH:MM:SS.ff')], default='hms', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cdr_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
