# SPDX-FileCopyrightText: Copyright 2026, Slinky Software
# SPDX-License-Identifier: GPL-3.0-only

"""Contextual help for AudioCodes SBC 7.4 SDR/CDR fields.

Help text is kept separate from the source models and can be overridden per key from the module
settings page. Termination-reason explanations are only shown when an administrator configures
them (``termination.<value>``); none are assumed here.
"""

from audiocodes_cdr.source_models import CDR_FIELDS, SDR_FIELDS

HELP_VERSION = 'AudioCodes SBC 7.4'
HELP_SOURCE = 'Summarised from public AudioCodes 7.4 SBC CDR documentation. Field names are not customised in this installation.'

HUNDREDTHS = 'Hundredths of a second; the raw value is shown alongside the formatted value.'
MEDIA_UNITS = 'Units are not assumed; thresholds apply only when configured with a unit.'

SDR_HELP = {
    'id': 'Database primary key of the SDR row in the source database.',
    'recordtype': 'Type of session record reported by the SBC.',
    'sessionid': 'SBC session identifier. All CDR legs of the same session on this SBC share this value; it links the SDR to its CDRs.',
    'setuptime': 'Time the session setup began (initial SIP INVITE). Used for search and statistics.',
    'connecttime': 'Time the session was answered/connected. Blank when the call never connected.',
    'releasetime': 'Time the session was released.',
    'timetoconnect': f'Time from setup until the session connected. {HUNDREDTHS}',
    'callduration': f'Connected duration of the session. {HUNDREDTHS} Stored as text in the source.',
    'sourceip': 'SIP signalling IP address of the originating (ingress) side.',
    'destinationip': 'SIP signalling IP address of the destination (egress) side.',
    'ingressipgroup': 'IP Group associated with the incoming leg.',
    'egressipgroup': 'IP Group associated with the outgoing leg.',
    'ingressani': 'Calling number (ANI) as received on the incoming leg.',
    'ingressdnis': 'Called number (DNIS) as received on the incoming leg.',
    'egressani': 'Calling number (ANI) as sent on the outgoing leg, after any number manipulation.',
    'egressdnis': 'Called number (DNIS) as sent on the outgoing leg, after any number manipulation.',
    'ingresscallid': 'SIP Call-ID header of the incoming leg.',
    'egresscallid': 'SIP Call-ID header of the outgoing leg.',
    'ingressremotertpip': 'Remote RTP (media) IP address on the incoming leg.',
    'ingressremotertpport': 'Remote RTP (media) port on the incoming leg.',
    'egressremotertpip': 'Remote RTP (media) IP address on the outgoing leg.',
    'egressremotertpport': 'Remote RTP (media) port on the outgoing leg.',
    'globalsessionid': 'Global Session ID. Stays the same as a call traverses multiple AudioCodes devices, so it may appear on records from other devices. Diagnostic only; not used to link CDRs.',
    'ingressterminationreason': 'SBC termination reason reported for the incoming leg.',
    'egressterminationreason': 'SBC termination reason reported for the outgoing leg.',
    'ingresssipterminationreason': 'SIP-level termination reason (SIP method or response) for the incoming leg.',
    'egresssipterminationreason': 'SIP-level termination reason (SIP method or response) for the outgoing leg.',
    'issuccess': 'Whether the SBC classified the session as successful. Blank means the outcome is unknown.',
}

CDR_HELP = {
    'id': 'Database primary key of the CDR row in the source database.',
    'cdrtype': 'Type of CDR generated by the SBC.',
    'reporttype': 'Report type of the CDR, i.e. the call stage at which it was generated.',
    'callid': 'SIP Call-ID header of this call leg.',
    'globalsessionid': 'Global Session ID of the call. Not included in CDRs unless CDR customisation enables it.',
    'sessionid': 'SBC session identifier shared with the SDR and the other legs of the session.',
    'legid': 'Identifier of the call leg within the session. A session can have more than two legs (forking, alternative routes, retries).',
    'callerdisplayid': 'Calling party display name.',
    'sourceusernamebeforemanip': 'Source user part (calling number) before number manipulation.',
    'sourceusername': 'Source user part (calling number) after number manipulation.',
    'sourcetags': 'Tags assigned to the source, as semicolon-separated key=value pairs.',
    'calleedisplayid': 'Called party display name.',
    'destinationusernamebeforemanip': 'Destination user part (called number) before number manipulation.',
    'destinationusername': 'Destination user part (called number) after number manipulation.',
    'destinationtags': 'Tags assigned to the destination, as semicolon-separated key=value pairs.',
    'sipinterfacename': 'SIP Interface used by this leg.',
    'ipgroupname': 'IP Group used by this leg.',
    'proxysetname': 'Proxy Set used by this leg.',
    'remoteip': 'Remote SIP signalling IP address of this leg.',
    'remoteport': 'Remote SIP signalling port of this leg.',
    'remotertpip': 'Remote RTP (media) IP address of this leg.',
    'remotertpport': 'Remote RTP (media) port of this leg.',
    'codertype': 'Audio coder (codec) negotiated for this leg.',
    'callorig': 'Call originator: RMT = remotely originated (inbound to the SBC), LCL = locally originated (outbound from the SBC).',
    'terminationside': 'Side that terminated the call leg (for example RMT for remote, LCL for local).',
    'cdrtrigger': 'Event that triggered generation of this CDR.',
    'alertingtime': f'Time from setup until alerting (ringing). {HUNDREDTHS}',
    'callduration': f'Connected duration of this leg. {HUNDREDTHS}',
    'wascallstarted': 'Whether the call leg reached the started (connected) state.',
    'callsuccess': 'Whether the SBC classified this leg as successful.',
    'setuptime': 'Time setup began for this leg.',
    'connecttime': 'Time this leg was connected. Blank when it never connected.',
    'releasetime': 'Time this leg was released.',
    'terminationreason': 'SBC termination reason for this leg.',
    'terminationreasoncategory': 'Category of the termination reason, as reported by the SBC.',
    'sipterminationreason': 'SIP-level termination reason (SIP method or response) for this leg.',
    'sipterminationdescription': 'SIP termination description (reason phrase or Reason header text) for this leg.',
    'terminationsideradius': 'Termination side in the form used for RADIUS accounting.',
    'terminationsideyesno': 'Termination side expressed as a yes/no flag, as reported by the SBC.',
    'terminationreasonvalue': 'Numeric value associated with the termination reason, as reported by the SBC.',
    'localjitter': f'Jitter measured locally by the SBC on received media. {MEDIA_UNITS}',
    'localpacketloss': f'Packet loss measured locally by the SBC on received media. {MEDIA_UNITS}',
    'localroundtripdelay': f'Round-trip delay measured locally by the SBC. {MEDIA_UNITS}',
    'remotejitter': f'Jitter reported by the remote endpoint (RTCP). {MEDIA_UNITS}',
    'remotepacketloss': f'Packet loss reported by the remote endpoint (RTCP). {MEDIA_UNITS}',
    'remoteroundtripdelay': f'Round-trip delay reported by the remote endpoint (RTCP). {MEDIA_UNITS}',
    'varcalluserdefined1': 'User-defined call variable 1, populated by SBC configuration (for example message manipulation).',
    'varcalluserdefined2': 'User-defined call variable 2, populated by SBC configuration (for example message manipulation).',
    'varcalluserdefined3': 'User-defined call variable 3, populated by SBC configuration (for example message manipulation).',
    'varcalluserdefined4': 'User-defined call variable 4, populated by SBC configuration (for example message manipulation).',
    'varcalluserdefined5': 'User-defined call variable 5, populated by SBC configuration (for example message manipulation).',
}

TOPIC_HELP = {
    'direction': 'CDR direction comes from the callorig field: RMT = inbound (remotely originated), LCL = outbound (locally originated). Any other value is shown as unknown. Direction is never inferred from leg ID, IP group or display order.',
    'correlation': 'CDRs are linked to the SDR by an exact sessionid match and ordered by leg ID then ID. Global Session ID and Call-ID are compared for diagnostics only.',
    'termination_reason': 'SBC termination reasons are shown exactly as reported. Explanations are shown only where an administrator has configured them.',
    'sip_termination_reason': 'SIP termination reasons are the SIP method or response that ended the leg, shown exactly as reported.',
    'timing': 'Durations are recorded in hundredths of a second (37501 = 375.01 s = 00:06:15.01). Times are shown in Australia/Sydney. When setup time is missing, connect time is shown and marked as a fallback.',
    'media_quality': f'Jitter, packet loss and round-trip delay are shown as reported. {MEDIA_UNITS}',
    'success': 'Success is the SBC classification. Blank values are shown as unknown and are never counted as successful or unsuccessful.',
}


def is_valid_override_key(key):
    if key.startswith('sdr.'):
        return key[4:] in SDR_FIELDS
    if key.startswith('cdr.'):
        return key[4:] in CDR_FIELDS
    if key.startswith('topic.'):
        return key[6:] in TOPIC_HELP
    if key.startswith('termination.'):
        return bool(key[12:].strip())
    return False


def build_field_help(overrides=None):
    overrides = overrides or {}
    sections = {
        'sdr': dict(SDR_HELP),
        'cdr': dict(CDR_HELP),
        'topics': dict(TOPIC_HELP),
        'termination_reasons': {},
    }
    targets = {'sdr.': 'sdr', 'cdr.': 'cdr', 'topic.': 'topics', 'termination.': 'termination_reasons'}
    for key, text in overrides.items():
        for prefix, section in targets.items():
            if key.startswith(prefix):
                sections[section][key[len(prefix):]] = text
                break
    return {'version': HELP_VERSION, 'source': HELP_SOURCE, **sections}
