# Generated by Django 5.2.15 on 2026-06-15 05:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=128)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], max_length=16)),
                ('actor_user_id_text', models.CharField(blank=True, default='', max_length=64)),
                ('actor_email', models.CharField(blank=True, default='', max_length=255)),
                ('actor_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('actor_auth_source', models.CharField(blank=True, default='', max_length=32)),
                ('object_type', models.CharField(blank=True, default='', max_length=64)),
                ('object_id_text', models.CharField(blank=True, default='', max_length=64)),
                ('object_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_number', models.CharField(blank=True, default='', max_length=64)),
                ('destination_number', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField()),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
